# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];


  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."swap".device = "/dev/disk/by-label/NIXCRYPTSWAP";
  boot.initrd.luks.devices."root".device = "/dev/disk/by-label/NIXCRYPTROOT";
  boot.initrd.luks.devices."home".device = "/dev/disk/by-label/NIXCRYPTHOME";

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "ext4";
  };


  fileSystems."/home" = {
    device = "/dev/mapper/home";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/mapper/swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
